# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20160322_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=250, upload_to='comments/posts/%Y/%m/%d', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(height_field='height', max_length=250, upload_to='comments/posts/%Y/%m/%d', verbose_name='Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('request', 'Request'), ('issue', 'Issue')], default='discussion', max_length=20, verbose_name='Category'),
        ),
    ]
